// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1zz2JBZzphRVEn6s_Gvk9b4rUZWBww5k',
    appId: '1:252643550630:web:17e6f42343898ae48a1b67',
    messagingSenderId: '252643550630',
    projectId: 'gestticket-5ce58',
    authDomain: 'gestticket-5ce58.firebaseapp.com',
    storageBucket: 'gestticket-5ce58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuGdqUDTgcdU4CqqTg3DDbObX3QwmyXxI',
    appId: '1:252643550630:android:c75d9751103c117e8a1b67',
    messagingSenderId: '252643550630',
    projectId: 'gestticket-5ce58',
    storageBucket: 'gestticket-5ce58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVpmr3jQMgeAgoEsQLOu7uTAFZ8QlvqFo',
    appId: '1:252643550630:ios:6447d7603b9353ec8a1b67',
    messagingSenderId: '252643550630',
    projectId: 'gestticket-5ce58',
    storageBucket: 'gestticket-5ce58.appspot.com',
    iosBundleId: 'com.example.gesttick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVpmr3jQMgeAgoEsQLOu7uTAFZ8QlvqFo',
    appId: '1:252643550630:ios:6447d7603b9353ec8a1b67',
    messagingSenderId: '252643550630',
    projectId: 'gestticket-5ce58',
    storageBucket: 'gestticket-5ce58.appspot.com',
    iosBundleId: 'com.example.gesttick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1zz2JBZzphRVEn6s_Gvk9b4rUZWBww5k',
    appId: '1:252643550630:web:bb511e772f4ea9418a1b67',
    messagingSenderId: '252643550630',
    projectId: 'gestticket-5ce58',
    authDomain: 'gestticket-5ce58.firebaseapp.com',
    storageBucket: 'gestticket-5ce58.appspot.com',
  );

}